
version: '2'
services:
  bitbucket:
    image: atlassian/bitbucket-server
    ports:
      - 7990:7990
      - 7999:7999
    volumes:
      - /tmp/bitbucket:/var/atlassian/application-data/bitbucket
